### ISSUE TITLE
FetchMany appears to adversely affect paging

### ISSUE THREAD

**Issue by jessetechie** [Lotpath/Querify#10]
It was my experience, after upgrading from 0.8.1 to 0.8.3, that calling FetchMany on a repository query caused the returned items to be less than the page size.  FetchMany performs a left outer join, which causes the result set to include a record for each child, rather than for each parent.  This in turn causes a page size of 10 to include only the first 10 children, not the first 10 parents.

First step is to write a failing test that will expose this bug.

**Comment by jeffdoolittle** [comment]
I'm not sure this is fixable with Querify.

http://stackoverflow.com/questions/9729262/nhibernate-linq-provider-and-take-skip-with-eager-fetching

If paging and Eager fetching are required, the simplest solution will probably be to define a service interface in your domain, and then implement the querying in the persistence project with more fine grained control over the generated Sql (using adhoc sql, or perhaps QueryOver syntax).
